print("IT IS THE FIRST PROGRAM IN PYTHON MADE BY MAYANK")
print("CALCULATOR")
a = input("Enter first no.=")
b = input("Enter second no.=")
print("addition=",int(a)+int(b))
print("subtraction=",int(a)-int(b))
print("multiplication=",int(a)*int(b))
print("division=",int(a)/int(b))
# print("exponential",int(a**3),int(b**3) )
print("modulus=",int(a)%int(b))
print("floor division",int(a)//int(b))